# Generated by Django 5.0 on 2026-01-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
