# Generated by Django 5.0 on 2026-01-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0008_alter_employee_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
